# Generated by Django 5.0.6 on 2024-06-05 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinfra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='typologie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appinfra.typologie'),
        ),
    ]
