# Generated by Django 5.0.6 on 2024-06-26 10:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinfra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='marque'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appinfra.brand', verbose_name='marque'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appinfra.place', verbose_name='adresse'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='quantité'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type_equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appinfra.type_equipment', verbose_name='type équipement'),
        ),
        migrations.AlterField(
            model_name='network',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appinfra.brand', verbose_name='marque'),
        ),
        migrations.AlterField(
            model_name='network',
            name='connection_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appinfra.type_connexion', verbose_name='type de connexion'),
        ),
        migrations.AlterField(
            model_name='network',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appinfra.place', verbose_name='adresse'),
        ),
        migrations.AlterField(
            model_name='network',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appinfra.provider', verbose_name='fournisseur'),
        ),
        migrations.AlterField(
            model_name='network',
            name='rank',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='rang'),
        ),
        migrations.AlterField(
            model_name='network',
            name='rescue',
            field=models.BooleanField(default=False, verbose_name='secour'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place',
            field=models.CharField(max_length=100, verbose_name='adresse'),
        ),
        migrations.AlterField(
            model_name='place',
            name='typology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appinfra.typologie', verbose_name='typologie'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='marque'),
        ),
        migrations.AlterField(
            model_name='software',
            name='administrator',
            field=models.CharField(max_length=100, verbose_name='administrateur'),
        ),
        migrations.AlterField(
            model_name='software',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='software',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appinfra.place', verbose_name='adresse'),
        ),
        migrations.AlterField(
            model_name='software',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appinfra.platform', verbose_name='plateforme'),
        ),
        migrations.AlterField(
            model_name='type_connexion',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='type_equipment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='typologie',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nom'),
        ),
    ]
