# Generated by Django 5.0.6 on 2024-06-14 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinfra', '0008_alter_software_place_alter_software_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appinfra.place'),
        ),
        migrations.AlterField(
            model_name='software',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appinfra.platform'),
        ),
    ]
