# Generated by Django 5.0.6 on 2024-06-18 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinfra', '0011_equipment_parent_delete_child_delete_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appinfra.brand'),
        ),
    ]
