# Generated by Django 5.0.6 on 2024-06-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinfra', '0013_equipment_software'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='name',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
