# Generated by Django 5.0.6 on 2024-06-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinfra', '0014_equipment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
