# Generated by Django 5.0.6 on 2024-05-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_band_year_formed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='year_formed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
