# Generated by Django 5.0.6 on 2024-06-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_listing_band'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='full name')),
            ],
        ),
    ]
