# Generated by Django 5.0.6 on 2024-06-06 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinfra', '0002_alter_place_typologie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Type_connexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Type_equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondary_type_connection', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(max_length=1000)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appinfra.place')),
                ('primary_brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appinfra.brand')),
                ('primary_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appinfra.provider')),
                ('primary_type_connection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appinfra.type_connexion')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('eligible', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=1000)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appinfra.brand')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appinfra.place')),
                ('type_equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appinfra.type_equipment')),
            ],
        ),
    ]
